# Generated by Django 5.2.5 on 2025-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='engagement_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='engagement_partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
