# Generated by Django 5.2.5 on 2025-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='total_revenue_days_p_cp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
