# Generated by Django 5.2.5 on 2025-08-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0002_revenueentry_engagement_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='billing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='collections',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
