# Generated by Django 5.2.5 on 2025-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0002_alter_contract_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueentry',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
