# Generated by Django 5.2.5 on 2025-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0003_revenueentry_billing_revenueentry_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueentry',
            name='bcv_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='monitor_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
