# Generated by Django 5.2.5 on 2025-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0003_alter_revenueentry_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueentry',
            name='bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='cp_ansr_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='duplicate_engagement_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='fytd_ansr_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='fytd_charged_hours',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='fytd_direct_cost_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='monitor_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='mtd_ansr_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='mtd_charged_hours',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='mtd_direct_cost_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
