# Generated by Django 5.2.5 on 2025-08-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_dashboard', '0004_alter_revenueentry_bcv_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenueentry',
            old_name='week',
            new_name='original_week_string',
        ),
    ]
